/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratoriopareja;

/**
 *
 * @author hnleo
 */
public class memoramaPantalla extends javax.swing.JFrame {

    /**
     * Creates new form memoramaPantalla
     */
    public memoramaPantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableroPanel = new javax.swing.JPanel();
        boton1_0 = new javax.swing.JButton();
        boton1_1 = new javax.swing.JButton();
        boton1_2 = new javax.swing.JButton();
        boton1_3 = new javax.swing.JButton();
        boton1_4 = new javax.swing.JButton();
        boton1_5 = new javax.swing.JButton();
        boton2_0 = new javax.swing.JButton();
        boton2_1 = new javax.swing.JButton();
        boton2_2 = new javax.swing.JButton();
        boton2_3 = new javax.swing.JButton();
        boton2_4 = new javax.swing.JButton();
        boton2_5 = new javax.swing.JButton();
        boton3_0 = new javax.swing.JButton();
        boton3_1 = new javax.swing.JButton();
        boton3_2 = new javax.swing.JButton();
        boton3_3 = new javax.swing.JButton();
        boton3_4 = new javax.swing.JButton();
        boton3_5 = new javax.swing.JButton();
        boton4_0 = new javax.swing.JButton();
        boton4_1 = new javax.swing.JButton();
        boton4_2 = new javax.swing.JButton();
        boton4_3 = new javax.swing.JButton();
        boton4_4 = new javax.swing.JButton();
        boton4_5 = new javax.swing.JButton();
        boton5_0 = new javax.swing.JButton();
        boton5_1 = new javax.swing.JButton();
        boton5_2 = new javax.swing.JButton();
        boton5_3 = new javax.swing.JButton();
        boton5_4 = new javax.swing.JButton();
        boton5_5 = new javax.swing.JButton();
        boton6_0 = new javax.swing.JButton();
        boton6_1 = new javax.swing.JButton();
        boton6_2 = new javax.swing.JButton();
        boton6_3 = new javax.swing.JButton();
        boton6_4 = new javax.swing.JButton();
        boton6_5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 700));
        setMinimumSize(new java.awt.Dimension(600, 700));
        setPreferredSize(new java.awt.Dimension(600, 700));
        setResizable(false);

        tableroPanel.setBackground(new java.awt.Color(255, 255, 204));
        tableroPanel.setMaximumSize(new java.awt.Dimension(600, 600));
        tableroPanel.setMinimumSize(new java.awt.Dimension(600, 600));
        tableroPanel.setLayout(new java.awt.GridLayout(6, 6));
        tableroPanel.add(boton1_0);
        tableroPanel.add(boton1_1);
        tableroPanel.add(boton1_2);
        tableroPanel.add(boton1_3);

        boton1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1_4ActionPerformed(evt);
            }
        });
        tableroPanel.add(boton1_4);
        tableroPanel.add(boton1_5);
        tableroPanel.add(boton2_0);
        tableroPanel.add(boton2_1);
        tableroPanel.add(boton2_2);
        tableroPanel.add(boton2_3);
        tableroPanel.add(boton2_4);
        tableroPanel.add(boton2_5);
        tableroPanel.add(boton3_0);
        tableroPanel.add(boton3_1);
        tableroPanel.add(boton3_2);
        tableroPanel.add(boton3_3);
        tableroPanel.add(boton3_4);
        tableroPanel.add(boton3_5);
        tableroPanel.add(boton4_0);
        tableroPanel.add(boton4_1);
        tableroPanel.add(boton4_2);
        tableroPanel.add(boton4_3);
        tableroPanel.add(boton4_4);
        tableroPanel.add(boton4_5);
        tableroPanel.add(boton5_0);
        tableroPanel.add(boton5_1);
        tableroPanel.add(boton5_2);
        tableroPanel.add(boton5_3);
        tableroPanel.add(boton5_4);
        tableroPanel.add(boton5_5);
        tableroPanel.add(boton6_0);
        tableroPanel.add(boton6_1);

        boton6_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6_2ActionPerformed(evt);
            }
        });
        tableroPanel.add(boton6_2);
        tableroPanel.add(boton6_3);
        tableroPanel.add(boton6_4);
        tableroPanel.add(boton6_5);

        getContentPane().add(tableroPanel, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 100));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("MEMORAMA");

        jLabel2.setText("Numero de Intentos: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton1_4ActionPerformed

    private void boton6_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton6_2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(memoramaPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(memoramaPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(memoramaPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(memoramaPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new memoramaPantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1_0;
    private javax.swing.JButton boton1_1;
    private javax.swing.JButton boton1_2;
    private javax.swing.JButton boton1_3;
    private javax.swing.JButton boton1_4;
    private javax.swing.JButton boton1_5;
    private javax.swing.JButton boton2_0;
    private javax.swing.JButton boton2_1;
    private javax.swing.JButton boton2_2;
    private javax.swing.JButton boton2_3;
    private javax.swing.JButton boton2_4;
    private javax.swing.JButton boton2_5;
    private javax.swing.JButton boton3_0;
    private javax.swing.JButton boton3_1;
    private javax.swing.JButton boton3_2;
    private javax.swing.JButton boton3_3;
    private javax.swing.JButton boton3_4;
    private javax.swing.JButton boton3_5;
    private javax.swing.JButton boton4_0;
    private javax.swing.JButton boton4_1;
    private javax.swing.JButton boton4_2;
    private javax.swing.JButton boton4_3;
    private javax.swing.JButton boton4_4;
    private javax.swing.JButton boton4_5;
    private javax.swing.JButton boton5_0;
    private javax.swing.JButton boton5_1;
    private javax.swing.JButton boton5_2;
    private javax.swing.JButton boton5_3;
    private javax.swing.JButton boton5_4;
    private javax.swing.JButton boton5_5;
    private javax.swing.JButton boton6_0;
    private javax.swing.JButton boton6_1;
    private javax.swing.JButton boton6_2;
    private javax.swing.JButton boton6_3;
    private javax.swing.JButton boton6_4;
    private javax.swing.JButton boton6_5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel tableroPanel;
    // End of variables declaration//GEN-END:variables
}
